version: '3'

volumes:
  db:
    driver: local

services:
  db:
    image: mysql:8.0.33-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./backend/src/database/scripts/init_user.sql:/docker-entrypoint-initdb.d/init_user.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: fake_jira
      MYSQL_USER: user123
      MYSQL_PASSWORD: password123

  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "3001:3001"
